apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: atlas
          mountPath: /cvmfs/atlas.cern.ch
        - name: atlas-condb
          mountPath: /cvmfs/atlas-condb.cern.ch
  volumes:
    - name: atlas
      flexVolume:
        driver: "cern/cvmfs"
        options:
          repository: "atlas.cern.ch"
    - name: atlas-condb
      flexVolume:
        driver: "cern/cvmfs"
        options:
          repository: "atlas-condb.cern.ch"
